language: php

services: mongodb

php:
  - 7.0

before_script:
  - echo 'extension=mongo.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer --prefer-source --dev install

script: phpunit --coverage-text --verbose
