language: php

sudo: true

services:
  - mongodb

php:
  - 7.0

before_script:
  - phpenv config-rm xdebug.ini
  - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer --prefer-source --no-interaction update

script: phpunit --coverage-text --verbose
